@startuml
!include _common.style

title Poker Game (Structure)
center footer project #1 - class diagram


package uqam.inf5153.poker {

  class Main {
    String result
    --
    + {static} main(args: String[])
    --
    - str2Array(s: String): String[]
    - findComb(cs: String[]): String
    - comp(p1: String, p2: String): String
    - maxVal(cs: String[]): Char
    - tie(p1: String, p2: String): String
    - getTable(): Map<Char, Int>
  }

  Class Carte{
  }

  Enum Valeur{
    1
    2
    3
    4
    5
    6
    7
    8
    9
    T
    J
    Q
    K
  }

  Enum Couleur{
    C
    H
    D
    S
  }

  class Mains{
    - cartes: ArrayList<Carte>
    - cartePlusForte() : Carte 
  }

  class Joueur{
    - id : String
    - main : Mains
    - victoires : int
  }

  class Partie{
    + resultat : String  //obtenir main gagnante du joueur
    - joueurs : ArrayList

  }

  Carte *-- "1" Valeur
  Carte *-- "1" Couleur
  Mains *-- Carte
  Joueur --> Mains
  Partie --> "2..*" Joueur
  Main --> Partie

}

@enduml
